# Generated by Django 4.1.4 on 2023-01-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='date_updated',
            field=models.DateField(auto_now=True),
        ),
    ]
